# Generated by Django 4.2.7 on 2023-11-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthPlace',
            fields=[
                ('birth_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProducts',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('children_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('study', models.BooleanField(default=False)),
                ('play_videogames', models.BooleanField(default=False)),
                ('videogames_platform', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CivilStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('home_phone', models.CharField(blank=True, max_length=20)),
                ('cell_phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('shipped_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceLocation',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('quantity_available', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.categoryproducts')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAditionalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.TextField(blank=True)),
                ('sports', models.TextField(blank=True)),
                ('civil_status', models.CharField(blank=True, max_length=50)),
                ('birth_place', models.ManyToManyField(blank=True, to='clients.birthplace')),
                ('children', models.ManyToManyField(blank=True, to='clients.children')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.customer')),
                ('interest_categories', models.ManyToManyField(blank=True, to='clients.categoryproducts')),
                ('place_location', models.ManyToManyField(blank=True, to='clients.placelocation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.orders')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.products')),
            ],
        ),
    ]
